### ISSUE TITLE
我觉得还是用 Disqus 吧……

### ISSUE THREAD

**Issue by FiveYellowMice** [KenOokamiHoro/kenookamihoro.github.io#2]
你受我的影响，可是我也没有不用 Disqus 呀😶。
Disqus 也不代表你会收集用户的隐私，它跟 Google Analytics 一样，你啥隐私也看不到的。
要说那些公司会收集隐私，那 Google Analytics 和 CloudFlare 也不该用，不是吗？但是那样我觉得没必要，所以 Disqus 也一样。

如果你不觉得我多管闲事的话：  
另外在网页里设评论系统很方便，也方便其他读者看到，很少有人会为评论一下或看一下评论专门点一下小链接/注册 GtHub 账号/注册你 Wki 的账号/翻墙/忍受 bug 重重且缓慢的 MediaWiki + CloudFlare 组合的。

**Comment by KenOokamiHoro** [comment]
嚎吧😂😂

**Comment by KenOokamiHoro** [comment]
已换，等会儿咱push上呗~

**Comment by FiveYellowMice** [comment]
好啊，不过我有两个疑问：
1. DNS 解析器难道不是域名提供商给的最好用吗？ CloudFlare 有什么优势？
2. 都有自己的服务器访问权限了为啥还要用 Google Analytics? 看服务器访问日志不就可以了？
