### ISSUE TITLE
visualeditor_for_mediawiki

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#28]
This issue is reserved for https://blog.yoitsu.moe/visualeditor_for_mediawiki.html

**Comment by FiveYellowMice** [comment]
Screen 后台运行不清真啊！你应该教教怎么使用 systemd service 。

**Comment by KenOokamiHoro** [comment]
😂😂😂
2016年8月10日 9:01 AM，Kaizhe Huang <notifications@github.com>写道：Screen 后台运行不清真啊！你应该教教怎么使用 systemd service 。

**Comment by mobking** [comment]
Horo骚年，汝可以看下汝的邮箱么

**Comment by KenOokamiHoro** [comment]
@mobking 啥？

**Comment by mobking** [comment]
T_T,我在创建一个百科，然后这个visualeditor扩展我一直安装不成功，然后最近搜到了你的博客文章，但是到了配置环节看不懂，还是没配置成功，所以我给你发了个邮件，希望得到你的帮助，可付费哦。。。

**Comment by KenOokamiHoro** [comment]
@mobking 然而没收到😂

**Comment by mobking** [comment]
T_T r z  
来个常用邮箱啥的吧我的哥～或者q啥的 我的110213488，加我啊

**Comment by KenOokamiHoro** [comment]
@mobking kenookamihoro@outlook.com 发给这个试试？

**Comment by mobking** [comment]
@KenOokamiHoro 也发过了，貌似依然石沉大海的模样  T_Tｒｚ

**Comment by habixiong** [comment]
docserver-http: HTTP 404
提示这个错误，这是为何？
可否指点一二
还有http://localhost:8000/汝设置的前缀/汝的wiki上的一个页面
这个能距个具体的格式例子吗？

**Comment by KenOokamiHoro** [comment]
@habixiong 现在大概是 `http://localhost:8000/域名/v3/page/html/汝的wiki上的一个页面 `了
例如这个 [https://parsoid.mediawikicn.org/wiki.yoitsu.moe/v3/page/html/首页/](https://parsoid.mediawikicn.org/wiki.yoitsu.moe/v3/page/html/首页/)

**Comment by FiveYellowMice** [comment]
mediawikicn.org ? 难道是公用的 Parsoid 服务器？

**Comment by KenOokamiHoro** [comment]
@FiveYellowMice 并不是 😂
