### ISSUE TITLE
在 blog.yoitsu.moe 上点博文链接跑到 .github.io 上了

### ISSUE THREAD

**Issue by FiveYellowMice** [KenOokamiHoro/kenookamihoro.github.io#3]
我猜这是一个小失误吧。

顺便提醒一下，为了避免搜索引擎爬到两个有同样内容但不同的 URL 而显示两个同样结果的惨状，最好设个 [cononical link](https://support.google.com/webmasters/answer/139066?hl=en) 。

**Comment by KenOokamiHoro** [comment]
pelican要求发布时一定要有SITEURL不然没法生成正确的RSS呐~

**Comment by FiveYellowMice** [comment]
对啊，所以更应该指定哪个是正式的网址了，不是吗？

然后我看到一堆在同源绝对链接前面加域名的 commit ……
