### ISSUE TITLE
N/A -- 觉得正文行距有点小

### ISSUE THREAD

**Issue by LastAvenger** [KenOokamiHoro/kenookamihoro.github.io#4]
用 Firefox 选中的时候会挡住一部分。
![2016-01-17-093649_705x143_scrot](https://cloud.githubusercontent.com/assets/8090459/12375450/c8fc08e0-bcfd-11e5-9cf4-dfb21d1906ac.png)

**Comment by KenOokamiHoro** [comment]
好吧咱一直在用chromium测试没注意😂😂

**Comment by KenOokamiHoro** [comment]
现在咧?:joy::joy:
