### ISSUE TITLE
#archlinux-cn 日报 -- 目录乱码

### ISSUE THREAD

**Issue by LastAvenger** [KenOokamiHoro/kenookamihoro.github.io#5]
Firefox 45.0.1

![2016-04-05-191341_309x315_scrot](https://cloud.githubusercontent.com/assets/8090459/14280041/ddd5b628-fb62-11e5-9e10-8fb039dea2ca.png)

**Comment by KenOokamiHoro** [comment]
为啥咱在本地测试的时候没有问题😂 ( CloudFlare出来背锅😂 😂
