### ISSUE TITLE
利用 CUPS 和 Samba 在 Arch Linux 和 Windows 间共享打印机

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#51]
这是文章 "利用 CUPS 和 Samba 在 Arch Linux 和 Windows 间共享打印机" (https://blog.yoitsu.moe/arch-linux/cups_sharing_printer.html) 的评论呗~

**Comment by farseerfc** [comment]
萌狼好棒！
不過可以繞過 samba 直接用 CUPS 連打印機啦，裝上合適的驅動就可以了。然後 CUPS 自帶雲共享來着，它自己就是個 IPP 服務器 https://wiki.archlinux.org/index.php/CUPS/Printer_sharing

**Comment by KenOokamiHoro** [comment]
@farseerfc 😋 先记下等干掉Windows用户以后再慢慢研究（雾

**Comment by farseerfc** [comment]
@KenOokamiHoro 233 不用幹(chi)掉 Windows 用戶了啦，Windows 可以用 IPP 連打印機的。 Linux + CUPS+打印機 就相當於一個有聯網服務的打印機了。只不過 Linux 這邊和 Windows 那邊都要裝對應的驅動而已。

**Comment by KenOokamiHoro** [comment]
@farseerfc 😋😋 fc好棒
