### ISSUE TITLE
Windows Subsystem for Linux + Arch Linux

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#53]
这是文章 "Windows Subsystem for Linux + Arch Linux" (https://blog.yoitsu.moe/security/arch-linux/wsl_with_arch_linux.html) 的评论呗~

**Comment by 068089dy** [comment]
wow

**Comment by KenOokamiHoro** [comment]
@068089dy 😋😋
