### ISSUE TITLE
给 GNU/Linux 萌新的 Arch Linux 安装指南

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#54]
这是文章 "给 GNU/Linux 萌新的 Arch Linux 安装指南" (https://blog.yoitsu.moe/arch-linux/installing_arch_linux_for_complete_newbies.html) 的评论呗~

**Comment by farseerfc** [comment]
萌狼棒！
補充一下，好像默認 base base-devel 不帶 wifi 相關的工具，萬一裝好之後進系統發現沒網還得修。
所以 `pacstrap` 的時候最好也帶上 `iw wpa_supplicant wpa_actiond` 這幾個，然後用 base 裏有的 `netctl/wifi-menu` 就能上 wifi 了。
（當然裝 NetworkManager 的話就不需要了）

**Comment by ZWindL** [comment]
萌狼棒！ ٩( ᐛ )و

**Comment by qin-nz** [comment]
我真的真的就不吐槽我最近半年装了5次都失败了……

**Comment by qin-nz** [comment]
应该是因为启动器的问题……
看了你的文章发现我用 grub 的时候好像漏了一个步骤

另外，grub 是不是不支持 surface pro 3 的安全启动啊？

**Comment by 068089dy** [comment]
大赞

**Comment by 068089dy** [comment]
还有一件事，日期是不是写错了

**Comment by KenOokamiHoro** [comment]
@068089dy 😂

**Comment by qin-nz** [comment]
改了日期之后，RSS又推送了一遍

**Comment by KenOokamiHoro** [comment]
@qin-nz 😂😂

**Comment by jiqingqing999** [comment]
给你个赞吧。

**Comment by gorgiaxx** [comment]
萌狼写的好棒！！

**Comment by Xanadu-Zen** [comment]
最后的“systemctl emable sddm”错了😂

**Comment by KenOokamiHoro** [comment]
@Xanadu-Zen 谢谢指正 😂

**Comment by hwdef** [comment]
xps15 9550按照uefi装的双系统，，磁盘分区是一个250g的ssd装win10，一个240gssd的其中100g装archlinux，其余140g当作windows的文件盘。。。。装完之后启动项中没有archlinux，，从我240g的ssd启动也会跳到windows，不知道是什么原因，

**Comment by KenOokamiHoro** [comment]
@hwdef 用的哪一种启动管理器？

Systemd-boot 的话需要自己写配置文件，像这样: https://wiki.archlinux.org/index.php/Systemd-boot#Configuration 😋 

GRUB 的话 grub-mkconfig 那一步没发现 Arch Linux 么 😂

**Comment by hwdef** [comment]
@KenOokamiHoro 用的grub，，额，安装的时候忘记看有没有 Arch Linux 了，，可能还是哪里弄错了。。之前装过manjaro没什么问题。。我再重装一遍试试

**Comment by bobby285271** [comment]
给个赞
