### ISSUE TITLE
编译 OpenWrt 和加入 Alljoyn Framework 支持

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#56]
这是文章 "编译 OpenWrt 和加入 Alljoyn Framework 支持" (https://blog.yoitsu.moe/tech_misc/compile_openwrt_and_add_alljoyn_framwork.html) 的评论呗~

**Comment by KenOokamiHoro** [comment]
（反正没人看）
即日起关闭全站 Disqus 评论，需要存档的可以电邮咱。

**Comment by yizhilee** [comment]
@KenOokamiHoro 明明有人在看的🙄。还是有点没太懂 AllJoyn 是用来干什么的，能举个实际应用的例子吗？

**Comment by KenOokamiHoro** [comment]
大概就是一个物联网通信框架‎吧2333                                                                                                                                                                                  ‎

**Comment by KenOokamiHoro** [comment]
反正咱就是把这个装到路由器上就好啦啦啦啦～

**Comment by imnepos** [comment]
啊，我是音業 。今天特意开设了 Github 帐号 来回帖。。。我很多心里话想说。。。
