### ISSUE TITLE
约伊兹的萌狼乡手札（首页） -- 多个问题

### ISSUE THREAD

**Issue by satgo1546** [KenOokamiHoro/kenookamihoro.github.io#6]
虽然不知道为什么会钻到这个站点来，但是既然有GitHub issue页的话，还是来吐槽一番好了。（？？？<br>\* 这issue列表好空啊。

 * 全站中西文间都有空格，然而右上角的“RSS订阅”就没有空格（这算啥问题啊
     * 不过很多文章里也是有无空格混用的……这就比较尴尬了
 * 右边栏中的“站点通告”下大小写不对：Github → GitHub
 * 右边栏中的“文章更新”中背景是浅蓝色，前景是白色（居然还特意加了个.fg-white），可辨识度极低

顺便说一下，Windows 10可以正确显示emoji（不过单色的很鬼畜……

不过说到底为啥这个站点会待在我的待读列表里呢……

**Comment by KenOokamiHoro** [comment]
哇终于有人来提问题啦好激动😂

有无空格这个好像是咱太随性啦？

**Comment by Tiexcn** [comment]
什么鬼，我也来回一下

**Comment by KenOokamiHoro** [comment]
:joy::joy::joy:
