### ISSUE TITLE
咱好像是累了？

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/kenookamihoro.github.io#62]
这是文章 "咱好像是累了？" (https://blog.yoitsu.moe/life/retire_for_a_while.html) 的评论呗~

**Comment by Jack-Works** [comment]
萌狼又要跑掉了吗……

**Comment by tcdw** [comment]
可怜的萌狼

**Comment by zhangyubaka** [comment]
会有人在意的呀。

**Comment by KenOokamiHoro** [comment]
@Jack-Works 不知道，不过咱在不在已经没有什么区别了 🤷

@tcdw 咱不值得谁去可怜 🤷

@zhangyubaka 🤷 ……

**Comment by FiveYellowMice** [comment]
萌狼要离开了啊。

“休息一下”的话，也就是意味着一段时间后还会回来的咯？我们会期待你回来的，好好休息。

**Comment by KenOokamiHoro** [comment]
最好不要有什么期待 🤷‍♀️
